export const appColors = {
  primary: '#007AFF',
  primaryDark: '#0056b3',
  primaryLight: '#5899DA',
  background: '#EBF4FA',
  card: '#FFFFFF',
  text: '#1A2B3C',
  secondaryText: '#5A6A7B',
  placeholderText: '#8FA4B8',
  buttonTextPrimary: '#FFFFFF',
  border: '#C5D9E8',
  addTaskButtonBackground: '#00A6FF',
  addTaskButtonText: '#FFFFFF',
  deleteButtonBackground: '#2A4A6C',
  deleteButtonText: '#FFFFFF',
  title: '#003D7A',
  success: '#50C8E8',
  switchThumbLight: '#FFFFFF',
  switchThumbDark: '#EBF4FA',
  switchTrackFalse: '#A0AEC0',
};